import cv2
import glob
import os

# RUN THIS FILE TO REMOVE BAD METADATA FROM TEMPLATES
# Generated by Gemini 3

def clean_png_metadata(folder):
    # Find all PNG files in the folder (and subfolders)
    # recursive=True allows it to look inside 'ranks' and 'suits' automatically
    files = glob.glob(os.path.join(folder, "**/*.png"), recursive=True)
    
    print(f"Found {len(files)} images. Cleaning...")

    for path in files:
        # 1. Read the image un-changed (preserves transparency if you have it)
        img = cv2.imread(path, cv2.IMREAD_UNCHANGED)
        
        if img is not None:
            # 2. Overwrite the file. 
            # cv2.imwrite generates a completely new PNG structure, 
            # dropping the corrupt 'iCCP' profile chunk.
            cv2.imwrite(path, img)
            
    print("Done! Warnings should be gone.")

if __name__ == "__main__":
    # Point this to your templates folder
    clean_png_metadata("templates")